### ISSUE TITLE
Hot reload error

### ISSUE THREAD

**Issue by lightway82** [AndreiMisiukevich/HotReload#138]
I use resources in page:
```
  <ContentPage.Resources>
        <Color x:Key="fgColor">#262626</Color>
        <Color x:Key="bgColor">White</Color>
        <Color x:Key="btnBgColor">Gray</Color>
    </ContentPage.Resources>
```

and hot reload throw error: [1]HotReloadAgent: ERROR: A resource with the key 'fgColor' is already present in the ResourceDictionary. [ArgumentException]

Am I doing something wrong or is it a bug?
I use 1.4 version for Rider 2020.2

**Comment by AndreiMisiukevich** [comment]
it more looks like a bug

**Comment by AndreiMisiukevich** [comment]
can you build a sample?

**Comment by lightway82** [comment]
[Sample](https://github.com/lightway82/TipCalculator)

**Comment by lightway82** [comment]
I disabled your plugin, but hot reload still working and throw same error. Rider has hot reload from 2020.1 and your plugin maybe conflict with it. I see error from your plugin in same moments

**Comment by lightway82** [comment]
I disabled jetbrains hot reload and enable your plugin again.  I added to App class 
``` 
#if DEBUG
            HotReloader.Current.Run(this); 
#endif
```
but hot reload is not working without errors

**Comment by AndreiMisiukevich** [comment]
I guess that's better to ask MS to fix the official hot reload

**Comment by AndreiMisiukevich** [comment]
Tried your sample on VS for Mac and it works fine with OFFICIAL hot reload
(You sample doesn't use my NuGet package BTW)

So I propose you to use an official one

**Comment by AndreiMisiukevich** [comment]
For using mine you should install a nuget package, disalbe official hot reload in settings, and enable our plugin

**Comment by lightway82** [comment]
I already installed Xamarin.HotReload, but hot reload not work

**Comment by AndreiMisiukevich** [comment]
> I already installed Xamarin.HotReload, but hot reload not work.
> What i do:
> 
> * use Windows
> * install Xamarin.HotReload
> * use #if DEBUG    HotReloader.Current.Run(this); #endif  in main class
> * enable rider plugin
> * run app as debug
> * activate hot reload

Do you try on Android or iOS?

**Comment by AndreiMisiukevich** [comment]
Anyways this issue isn't related to plugin.
Can you reproduce this bug on Visual Studio? (For Win or Mac)

**Comment by lightway82** [comment]
I try for android.
I can test project on VS tomorrow

**Comment by AndreiMisiukevich** [comment]
> I try for android.
> I can test project on VS tomorrow

Yes, please do it

**Comment by lightway82** [comment]
This error stack trace appear after launch rider and run app in  debug configuration. Maybe it prevent plugin  normal working
``` 
Should be called at least in the state COMPONENTS_LOADED, the current state is: CONFIGURATION_STORE_INITIALIZED
Current violators count: 1



java.lang.Throwable
	at com.intellij.diagnostic.LoadingState.logStateError(LoadingState.java:63)
	at com.intellij.diagnostic.LoadingState.checkOccurred(LoadingState.java:59)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.<init>(ActionManagerImpl.java:159)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:47)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:664)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:49)
	at com.intellij.serviceContainer.ServiceComponentAdapter.access$createAndInitialize(ServiceComponentAdapter.kt:13)
	at com.intellij.serviceContainer.ServiceComponentAdapter$doCreateInstance$1.run(ServiceComponentAdapter.kt:43)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:192)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:42)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:413)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:395)
	at com.intellij.openapi.actionSystem.ActionManager.getInstance(ActionManager.java:28)
	at hotreload.extension.rider.component.StartUpProjectComponent.<init>(StartUpProjectComponent.kt:18)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:47)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:664)
	at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:35)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:60)
	at com.intellij.serviceContainer.ComponentManagerImpl.createComponents(ComponentManagerImpl.kt:260)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$loadComponents$5(ApplicationImpl.java:346)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl.loadComponents(ApplicationImpl.java:346)
	at com.intellij.idea.ApplicationLoader$startApp$6$loadComponentInEdtFuture$1.run(ApplicationLoader.kt:193)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:322)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:132)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:188)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:419)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by AndreiMisiukevich** [comment]
CC @iBavtovich

**Comment by iBavtovich** [comment]
Fixed :) @lightway82 plugin v.1.4.4. will be available for downloading/update in Rider in 1-2 days.

**Comment by AndreiMisiukevich** [comment]
> Fixed :) @lightway82 plugin v.1.4.4. will be available for downloading/update in Rider in 1-2 days.

Awesome work 👍

**Comment by lightway82** [comment]
Nice, thanks! 
G.J.!

**Comment by AndreiMisiukevich** [comment]
Feel free to reopen if the bug still exists once a new version is released
